{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GglLfr.MindustryClient",
    "module": "info",
    "version": "v1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "info-v1.1.1.jar",
          "url": "info-v1.1.1.jar",
          "size": 5205,
          "sha512": "43c09d099c787383f8ec6f1d8b46881c52211bc0116da853d4246f9c1a97ffc3d7fd14c84c1e717edfbd5182e2922ff871e29e04e82cafbcc7cee5a502d937d4",
          "sha256": "e576cd9c7058c593de952746b987a4fc47f00ba7b28e14c1ceeedfafea98fefa",
          "sha1": "f23aca4c7f01cd4b053561448ace3863569c5c2b",
          "md5": "e94f5fdae4619a5a688cebf6c0226e4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "info-v1.1.1.jar",
          "url": "info-v1.1.1.jar",
          "size": 5205,
          "sha512": "43c09d099c787383f8ec6f1d8b46881c52211bc0116da853d4246f9c1a97ffc3d7fd14c84c1e717edfbd5182e2922ff871e29e04e82cafbcc7cee5a502d937d4",
          "sha256": "e576cd9c7058c593de952746b987a4fc47f00ba7b28e14c1ceeedfafea98fefa",
          "sha1": "f23aca4c7f01cd4b053561448ace3863569c5c2b",
          "md5": "e94f5fdae4619a5a688cebf6c0226e4b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "info-v1.1.1-javadoc.jar",
          "url": "info-v1.1.1-javadoc.jar",
          "size": 4157229,
          "sha512": "2c4943424544ee273306a76d6628a1dca33d80d1292be990502da9c96fa9505c5a6ee599c61ae1039efa556b7e1c4d366ab632210d41d055db46962cde3f9022",
          "sha256": "538e79459d9d72d3524015f2ff1f077cfde02ad246a2e11710784a3b89fa8cd8",
          "sha1": "2dc0647bd1a3cd1af36a2bb57bbaad07eb03de7b",
          "md5": "fd4ce3653aff23aeafdc6f6d266024ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "info-v1.1.1-sources.jar",
          "url": "info-v1.1.1-sources.jar",
          "size": 2451,
          "sha512": "a92408213a2577f599f9089aa6df72591fc033669f96c74d04df8baec5c1ac9eb3d0c1a310c8331d6a3dc589c41bacb5599fe0b2e4832235606275827f6ca2ea",
          "sha256": "00d57fd24817018fd4bb89568dd5157c98c1c8993a0875d56e14f2dd68684002",
          "sha1": "2134919c55958182a975899b196ed92d764d09c2",
          "md5": "9503c0afcd0973be713b98653b870d38"
        }
      ]
    }
  ]
}
